### PR TITLE
Allows attachment content to be a string

### PR DESCRIPTION
**Pull request by jmnsf**
When a message includes an emoji, for example, it's sent as an attachment, and the content will be a string of html. Example:

```elixir
%{
  "attachments" => [
    %{
      "contentType" => "image/*", 
      "contentUrl" => "https://statics.teams.microsoft.com/evergreen-assets/skype/v2/smile/50.png"
    }, 
    %{
      "content" => "<div><div><span class=\"animated-emoticon-50-smile\" title=\"Smiley\" type=\"(smile)\"><img itemid=\"smile\" itemscope=\"\" itemtype=\"http://schema.skype.com/Emoji\" src=\"https://statics.teams.microsoft.com/evergreen-assets/skype/v2/smile/50.png\" alt=\"≡ƒÿä\" style=\"width:50px; height:50px\"></span></div>\n</div>", 
      "contentType" => "text/html"
    }
  ]
  # ...
}
```

### CODE REVIEW

**Comment by zabirauf** [comment]
@jmnsf Is that documented on bot framework documentation? I couldn't find it as part of https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#attachment-object 
If not then we should certainly open a bug for their documentation.

**Comment by jmnsf** [comment]
@zabirauf nope. This is probably a peculiarity of Microsoft Teams though, I suspect different channels will have slightly different behaviors. The closest [docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-message-format#formatting-text-content) I could find are related to the message format, but they don't mention this text-as-html-attachment peculiarity.

I'd go so far as to say this is a MS Teams bug actually, emojis should be regular encoded characters, how they're presented and at what size is the client's concern... Unsure they're very open to bug reportsm however, considering the sheer amount of them 🙂

**Comment by zabirauf** [comment]
@jmnsf Looking at the type in [C# documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.schema.attachment.content?view=botbuilder-dotnet-stable#Microsoft_Bot_Schema_Attachment_Content) it specific it as an `object` which in `C#` could be anything i.e. number, string or class etc. So it make sense that it can be string here as well. Do we also want to make it more generic by adding `integer | float | boolean` in the type spec?

**Comment by jmnsf** [comment]
@zabirauf good question... I think the equivalent in Elixir would be `any`, right? I'm inclined to avoiding generalizing the type before seeing evidence that it's necessary (with an example like the above with an integer content for example, or MS docs) because this way we have stronger support from the compiler's type checking. What do you think?

**Comment by zabirauf** [comment]
@jmnsf I agree that we shouldn't use `any`. But we should use the types that a json allows e.g. string, number, boolean, array, map. So I think they will map to 

```
@type JsonBaseValue :: String.t | number | boolean
@type JsonObject :: JsonBaseValue  | [JsonBaseValue] | %{optional(String.t) => JsonObject}
```

**Comment by jmnsf** [comment]
@zabirauf sorry about the delay, changes done. There's an issue with the build though 🙂

**Comment by jmnsf** [comment]
@zabirauf do you have a while to take a look at this please? :)

**Comment by jmnsf** [comment]
@zabirauf _please_? 🙏🏼

**Comment by bololabs** [comment]
@jmnsf sorry, I thought I already merged this. Thanks for the ping. I’ll confirm the build issue and merge it in a day.

**Comment by zabirauf** [comment]
@jmnsf sorry, I thought I already merged this. Thanks for the ping. I’ll confirm the build issue and merge it in a day

**Pull request merged**
